### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by CordyW** [easychen/CookieCloud#6]
浏览器插件提示：测试失败，请检查填写的信息是否正确；
服务端提示：
Server start on http://localhost:8088
PayloadTooLargeError: request entity too large
    at Gunzip.onData (/data/api/node_modules/raw-body/index.js:253:12)
    at Gunzip.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Gunzip.Readable.push (node:internal/streams/readable:228:10)
    at Zlib.processCallback (node:zlib:566:10) {
  limit: 102400,
  received: 114688,
  type: 'entity.too.large'
}

**Comment by easychen** [comment]
用这个版本及以后的镜像 easychen/cookiecloud:2023.01.19.14.37

**Comment by zcluo** [comment]
刚刚啦了latest的镜像以及用node部署都报同样的错误
镜像：
PayloadTooLargeError: request entity too large
    at Gunzip.onData (/data/api/node_modules/raw-body/index.js:253:12)
    at Gunzip.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Gunzip.Readable.push (node:internal/streams/readable:228:10)
    at Zlib.processCallback (node:zlib:566:10) {
  limit: 102400,
  received: 104657,
  type: 'entity.too.large'

node部署：
PayloadTooLargeError: request entity too large
    at Gunzip.onData (/root/CookieCloud/api/node_modules/raw-body/index.js:253:12)
    at Gunzip.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Gunzip.Readable.push (_stream_readable.js:213:10)
    at Gunzip.Transform.push (_stream_transform.js:152:32)
    at Zlib.processCallback (zlib.js:538:10) {
  limit: 102400,
  received: 114688,
  type: 'entity.too.large'
}
